GET http://localhost:8080/api/albums

###
GET http://localhost:8080/api/albums/8/

###

PATCH http://localhost:8080/api/albums/8/addsong/
Content-Type: application/json

{
"songTitle": "Dream Team",
"songDuration": "3",
"songLink": "Link",
"songImage": "Img"
}

###

DELETE http://localhost:8080/api/albums/8/